#!/usr/bin/env bash
#creating the while loop
y=1
while [ $y -le 10 ]
do
	if [ $y -eq 4 ]
	then
		echo "bad luck"
	elif [ $y -eq 8 ]
	then
		echo "good lcuk"
	else
		echo "Best School"
	fi
	((y++))
done
