#!/usr/bin/env bash
#creating a script that uses a case statements
y=1
while [ $y -le 20 ]
do
	echo "$y"
	case $x in
		4)
			echo "bad luck from china"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((y++))
done
